Revert "Build hdp images on top of previous releases"
This reverts commit adcb535710129b2fc71484b2c7167431921a58a1.

diff --git a/testing/hdp2.6-hive/Dockerfile b/testing/hdp2.6-hive/Dockerfile
--- a/testing/hdp2.6-hive/Dockerfile
+++ b/testing/hdp2.6-hive/Dockerfile
@@ -10,16 +10,56 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-# Use last layer from ghcr.io/trinodb/testing/hdp2.6-hive:38
-FROM 6439b9f223a1
+FROM testing/centos6-oj8:unlabelled
+
+# Change default timezone
+RUN ln -snf "/usr/share/zoneinfo/Asia/Kathmandu" /etc/localtime && echo "Asia/Kathmandu" > /etc/timezone
+
+# Install HDP repo
+RUN set -xeu; \
+    wget -nv http://public-repo-1.hortonworks.com/HDP/centos6/2.x/updates/2.6.5.0/hdp.repo -P /etc/yum.repos.d; \
+    wget -nv http://public-repo-1.hortonworks.com/HDP-GPL/centos6/2.x/updates/2.6.5.0/hdp.gpl.repo -P /etc/yum.repos.d; \
+    echo OK
+
+# Install Hadoop, Hive (w/ MySQL)
+RUN yum install -y \
+    hadoop-hdfs-namenode \
+    hadoop-hdfs-secondarynamenode \
+    hadoop-hdfs-datanode \
+
+    hadoop-yarn-resourcemanager \
+    hadoop-yarn-nodemanager \
+
+    hive \
+    hive-metastore \
+    hive-server2 \
+
+    hadooplzo \
+    hadooplzo-native \
+    lzo \
+    lzo-devel \
+    lzop \
+
+    mysql-server mysql-connector-java \
+    libxslt \
+
+# Cleanup
+  && yum -y clean all && rm -rf /tmp/* /var/tmp/* \
+  && ln -s /usr/share/java/mysql-connector-java.jar /usr/hdp/current/hive-metastore/lib/mysql-connector-java.jar
+
+# Delete original configuration
+RUN rm -r /etc/hadoop/conf/* \
+  && rm -r /etc/hive/conf/*
 
 # Copy configuration files
 COPY ./files /
 
-# Remove old SSH keys
-RUN rm -Rf /root/.ssh/* /etc/ssh/ssh_host_rsa_key /etc/ssh/ssh_host_dsa_key
+# Run setup script
+RUN /root/setup.sh \
+  && rm -rf /tmp/* /var/tmp/*
 
 # Setup sock proxy
+RUN yum install -y openssh openssh-clients openssh-server && yum -y clean all
 RUN ssh-keygen -t rsa -b 4096 -C "automation@trino.io" -N "" -f /root/.ssh/id_rsa \
   && ssh-keygen -t rsa -b 4096 -N "" -f /etc/ssh/ssh_host_rsa_key \
   && ssh-keygen -t dsa -b 1024 -N "" -f /etc/ssh/ssh_host_dsa_key \
@@ -33,7 +73,6 @@ RUN set -xeu; \
     for user in root hive hdfs; do \
         # ~hive might be owned by root
         chown -R "${user}:" "$(eval echo ~"${user}")"; \
-        sudo -u "${user}" bash -c ' echo "" > ~/.bash_history '; \
         sudo -u "${user}" bash -c ' echo "netstat -ltnp" >> ~/.bash_history '; \
         sudo -u "${user}" bash -c ' echo "beeline -u jdbc:hive2://localhost:10000/default -n hive" >> ~/.bash_history '; \
         sudo -u "${user}" bash -c ' echo "hadoop dfs -ls -R /user/hive/warehouse" >> ~/.bash_history '; \
